### PR TITLE
Widget and button

### PR DESCRIPTION
**Pull request by Trumbore**
## Purpose

This submission adds a "Create RMap DiSCO" button to the title bar of the RMap widget
that was introduced to the OSF web site in the prevous submission.  Clicking the button
raises a modal dialog warning the users of the consequences of this action and asking
them to confirm the decision.  Confirmation causes a server request to be made that
will create the DiSCO and displays the resulting graph in the widget.
## Changes

The profile.mako and project.mako files now pass arguments to the widget template
that indicate whether the current node is for a user, a registration, or a private
project/component.  The node's unique ID is also determined during the Mako
pre-processing and is passed to the widget.

When a DiSCO is to be created, the JavaScript code calls a new local server, run on
port 7000.  This server provides the necessary credentials when calling the RMap
server to request the DiSCO creation.  That call returns the new DiSCO's ID, which in
turn is returned to JavaScript for use when displaying the graph.  The new server
must be started along with all the other servers and processes required by the OSF
site.  On Linux, it is started simply with:

```
cd osf.io/rmap
./rmap_cgi_server.py &
```

In order for the RMap server to call back to the OSF API server, it was changed to
listen to requests from all IP addresses.  The OSF web server was changed to listen
to the local IP address 127.0.0.1.  It is likely that these values could be modified
to provide a more secure site.

The modal confirmation dialog was derived from similar Bootstrap code found elsewhere
in the OSF site.  To overcome a zooming problem in the widget when it was collapsed
and expanded again, event handlers were added to hide the widget during the animated
collapse/expand operations.
## Side effects

Additional development would be needed to make this functionality robust enough
for deployment.  In particular, only minimal effort is made to ensure that the call to
the RMap server succeeds, and no error messages are reported.  Numerous issues
could arise in this area, from the server being down to the OSF server credentials or
authorization being incorrect, to the OSF server being unreachable from the RMap
server.
## Ticket

[JIRA Ticket DC-2363](https://scm.dataconservancy.org/issues/browse/DC-2363)

### CODE REVIEW

**Comment by markpatton** [comment]
Looks good. I wonder if it makes sense to put this into a branch rmap-integration given that other development like the fedora work is going into a branch?

**Comment by Trumbore** [comment]
That makes sense to me.  I don't imagine that would be too hard - would I need to create a new pull request, or can I modify this one?

**Comment by markpatton** [comment]
I believe you would have to create a branch with your code and create a new pr.

**Comment by emetsger** [comment]
@Trumbore @markpatton @htpvu  I'm closing this PR in favor of #3 which is against the 'feature/rmap-widget' branch.

**Pull request closed without merging**
